source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'SpeakNow.xcodeproj'
platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '~> 3.0'
pod 'KeychainSwift', '~> 3.0'
pod "FlexibleTableView"
pod 'Material', '~> 1.0'
pod 'KVNProgress'
pod 'SwiftyJSON'
pod 'MJRefresh'
pod 'Kingfisher', '~> 2.0'
