platform :ios, '8.0'
project 'SpeakNow.xcodeproj'

target "SpeakNow" do
	use_frameworks!
	
	pod "FlexibleTableView"
	pod 'Alamofire', '3.5.0'
	pod 'JSQMessagesViewController'
	pod 'KeychainSwift', git: 'https://github.com/marketplacer/keychain-swift.git', branch: 'swift_2_3'
	pod 'Kingfisher', '2.6.1'
	pod 'KVNProgress'
	pod 'Material', git: 'https://github.com/CosmicMind/Material.git', branch: 'swift-2.3'
	pod 'MJRefresh'
	pod 'SwiftyJSON','2.4.0'
	pod 'AVOSCloud'        
	pod 'AVOSCloudIM'   
end

source 'https://github.com/CocoaPods/Specs.git'
